{% set version = "1.0" %}

package:
    name: mpas_analysis
    version: {{ version }}

source:
    path: ../..

build:
    number: 0
    script: $PYTHON setup.py install --single-version-externally-managed
            --record=record.txt
    noarch: python

test:
    requires:
        - pytest
    imports:
        - mpas_analysis
        - pytest
    commands:
        - pytest --pyargs mpas_analysis

requirements:
    build:
        - python
        - setuptools
    run:
        - python
        - numpy
        - scipy
        - matplotlib
        - netcdf4
        - xarray >=0.10.0
        - dask
        - bottleneck
        - basemap
        - lxml
        - nco >=4.7.0
        - pillow
        - cmocean
        - progressbar2
        - requests

about:
    home:  http://gitub.com/MPAS-Dev/MPAS-Analysis
    license: BSD 3-Clause
    license_file: LICENSE
    summary: 'Analysis of MPAS-Ocean and MPAS-Seaice simulations results'

extra:
    recipe-maintainers:
        - doutriaux1
        - xylar

