channels:
  - conda-forge
dependencies:
  - pytest
  - six
  - numpy
  - scipy
  - lxml
  - xarray
  - matplotlib
  - dask
  - netcdf4
  - hdf5
  - hdf4
  - nco
  - pyproj
  - pillow
  - cmocean
  - progressbar2
  - requests
